name: ci
on:
  push:
    tags:
      - '*'
permissions:
  contents: write
  pull-requests: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Install Python dependencies
        run: pip install -r ./docs/pip-requirements.txt
      - name: Configure git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Deploy docs to a temporary branch
        run: |
          VERSION=${{ github.ref }}
          VERSION=${VERSION#refs/tags/}
          BASE_VERSION=${VERSION#v}
          FULL_VERSION="v$BASE_VERSION"
          echo "Deploying documentation for version: $FULL_VERSION"
          cd docs
          mike deploy --update-aliases $BASE_VERSION latest
          cd ..
          ls -d */
          git checkout -b docs-$VERSION
          git branch
          git ls-files | grep -v '^docs/build/' | xargs git rm -f
          
          git add -f docs/build/*
          
          git commit -m "Update documentation for version $FULL_VERSION"
          git push origin docs-$FULL_VERSION
          echo "::set-output name=version::$VERSION"


      - name: Create pull request for docs deployment
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: gh-pages
          head: docs-${{ steps.deploy-docs.outputs.version }}
          title: "Update docs for version ${{ steps.deploy-docs.outputs.version }}"
          body: "This PR updates the documentation for version ${{ steps.deploy-docs.outputs.version }}."

      - name: Notify about PR
        run: echo "Pull request created ${{ steps.create_pr.outputs.pr_url }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}