name: ci

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Install Python dependencies
        run: pip install -r ./docs/pip-requirements.txt

      - name: Configure git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Deploy docs to gh-pages
        run: |
          VERSION=${{ github.ref }}
          VERSION=${VERSION#refs/tags/}
          BASE_VERSION=${VERSION#v}
          FULL_VERSION="v$BASE_VERSION"

          echo "Deploying documentation for version: $FULL_VERSION"

          cd docs
          mike deploy --update-aliases $BASE_VERSION latest

          # Ensure `docs/build` is removed if generated
          rm -rf build
          
          cd ..
          git fetch origin gh-pages
          git checkout gh-pages
          git pull origin gh-pages

          git add .
          git commit -m "Update documentation for version $FULL_VERSION"
          git push origin gh-pages
          
      - name: Notify about PR
        run: echo "Pull request created ${{ steps.create_pr.outputs.pr_url }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
