name: ci
on:
  push:
    tags:
      - '*'
permissions:
  contents: write
  pull-requests: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Install Python dependencies
        run: pip install -r ./docs/pip-requirements.txt
      - name: Configure git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Deploy docs to a temporary branch
        run: |
          VERSION=${{ github.ref }}
          VERSION=${VERSION#refs/tags/}
          BASE_VERSION=${VERSION#v}
          FULL_VERSION="v$BASE_VERSION"
          echo "Deploying documentation for version: $FULL_VERSION"
          cd docs
          mike deploy --update-aliases $BASE_VERSION latest
          cd ..
          ls -d */
          git checkout -b docs-$VERSION
          git branch
          git ls-files | grep -v '^docs/build/' | xargs git rm -f
          
          git add -f docs/build/*
          
          git commit -m "Update documentation for version $FULL_VERSION"
          git push origin docs-$FULL_VERSION
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: create pull request
        run: gh pr create -B docs-${{ env.version }} -H gh-pages --title 'Merge docs-${{ env.version }} into gh-pages' --body 'Created by Github action'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify about PR
        run: echo "Pull request created ${{ steps.create_pr.outputs.pr_url }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}